# TCL File Generated by Component Editor 13.0sp1
# Fri Sep 20 22:28:24 EDT 2019
# DO NOT MODIFY


# 
# avalon_div64 "avalon_div64" v1.0
#  2019.09.20.22:28:24
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avalon_div64
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_div64
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_div64
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_div64
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_div64.v VERILOG PATH ../hw/avalon_div64.v TOP_LEVEL_FILE
add_fileset_file div.v VERILOG PATH ../hw/div.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point div_cpu
# 
add_interface div_cpu avalon end
set_interface_property div_cpu addressUnits WORDS
set_interface_property div_cpu associatedClock clock
set_interface_property div_cpu associatedReset reset
set_interface_property div_cpu bitsPerSymbol 8
set_interface_property div_cpu burstOnBurstBoundariesOnly false
set_interface_property div_cpu burstcountUnits WORDS
set_interface_property div_cpu explicitAddressSpan 0
set_interface_property div_cpu holdTime 0
set_interface_property div_cpu linewrapBursts false
set_interface_property div_cpu maximumPendingReadTransactions 0
set_interface_property div_cpu readLatency 0
set_interface_property div_cpu readWaitStates 0
set_interface_property div_cpu readWaitTime 0
set_interface_property div_cpu setupTime 0
set_interface_property div_cpu timingUnits Cycles
set_interface_property div_cpu writeWaitTime 0
set_interface_property div_cpu ENABLED true
set_interface_property div_cpu EXPORT_OF ""
set_interface_property div_cpu PORT_NAME_MAP ""
set_interface_property div_cpu SVD_ADDRESS_GROUP ""

add_interface_port div_cpu div_address address Input 3
add_interface_port div_cpu div_byteenable byteenable Input 8
add_interface_port div_cpu div_chipselect chipselect Input 1
add_interface_port div_cpu div_write write Input 1
add_interface_port div_cpu div_writedata writedata Input 64
add_interface_port div_cpu div_readdata readdata Output 64
set_interface_assignment div_cpu embeddedsw.configuration.isFlash 0
set_interface_assignment div_cpu embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment div_cpu embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment div_cpu embeddedsw.configuration.isPrintableDevice 0


# 
# connection point div_intr
# 
add_interface div_intr interrupt end
set_interface_property div_intr associatedAddressablePoint div_cpu
set_interface_property div_intr associatedClock clock
set_interface_property div_intr associatedReset reset
set_interface_property div_intr ENABLED true
set_interface_property div_intr EXPORT_OF ""
set_interface_property div_intr PORT_NAME_MAP ""
set_interface_property div_intr SVD_ADDRESS_GROUP ""

add_interface_port div_intr div_irq irq Output 1


# 
# connection point div_ledg
# 
add_interface div_ledg conduit end
set_interface_property div_ledg associatedClock clock
set_interface_property div_ledg associatedReset reset
set_interface_property div_ledg ENABLED true
set_interface_property div_ledg EXPORT_OF ""
set_interface_property div_ledg PORT_NAME_MAP ""
set_interface_property div_ledg SVD_ADDRESS_GROUP ""

add_interface_port div_ledg div_led export Output 8

