# TCL File Generated by Component Editor 13.0sp1
# Sun Sep 22 10:58:39 EDT 2019
# DO NOT MODIFY


# 
# avalon_prd_cnt "avalon_prd_cnt" v1.0
#  2019.09.22.10:58:39
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avalon_prd_cnt
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_prd_cnt
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_prd_cnt
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_prd_cnt
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_prd_cnt.v VERILOG PATH ../hw/avalon_prd_cnt.v TOP_LEVEL_FILE
add_fileset_file prd_cnt.v VERILOG PATH ../hw/prd_cnt.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point prd_cnt_cpu
# 
add_interface prd_cnt_cpu avalon end
set_interface_property prd_cnt_cpu addressUnits WORDS
set_interface_property prd_cnt_cpu associatedClock clock
set_interface_property prd_cnt_cpu associatedReset reset
set_interface_property prd_cnt_cpu bitsPerSymbol 8
set_interface_property prd_cnt_cpu burstOnBurstBoundariesOnly false
set_interface_property prd_cnt_cpu burstcountUnits WORDS
set_interface_property prd_cnt_cpu explicitAddressSpan 0
set_interface_property prd_cnt_cpu holdTime 0
set_interface_property prd_cnt_cpu linewrapBursts false
set_interface_property prd_cnt_cpu maximumPendingReadTransactions 0
set_interface_property prd_cnt_cpu readLatency 0
set_interface_property prd_cnt_cpu readWaitStates 0
set_interface_property prd_cnt_cpu readWaitTime 0
set_interface_property prd_cnt_cpu setupTime 0
set_interface_property prd_cnt_cpu timingUnits Cycles
set_interface_property prd_cnt_cpu writeWaitTime 0
set_interface_property prd_cnt_cpu ENABLED true
set_interface_property prd_cnt_cpu EXPORT_OF ""
set_interface_property prd_cnt_cpu PORT_NAME_MAP ""
set_interface_property prd_cnt_cpu SVD_ADDRESS_GROUP ""

add_interface_port prd_cnt_cpu write_data writedata Input 32
add_interface_port prd_cnt_cpu write write Input 1
add_interface_port prd_cnt_cpu read_data readdata Output 32
set_interface_assignment prd_cnt_cpu embeddedsw.configuration.isFlash 0
set_interface_assignment prd_cnt_cpu embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment prd_cnt_cpu embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment prd_cnt_cpu embeddedsw.configuration.isPrintableDevice 0


# 
# connection point prd_cnt_itr
# 
add_interface prd_cnt_itr interrupt end
set_interface_property prd_cnt_itr associatedAddressablePoint prd_cnt_cpu
set_interface_property prd_cnt_itr associatedClock clock
set_interface_property prd_cnt_itr associatedReset reset
set_interface_property prd_cnt_itr ENABLED true
set_interface_property prd_cnt_itr EXPORT_OF ""
set_interface_property prd_cnt_itr PORT_NAME_MAP ""
set_interface_property prd_cnt_itr SVD_ADDRESS_GROUP ""

add_interface_port prd_cnt_itr irq irq Output 1


# 
# connection point sig
# 
add_interface sig conduit end
set_interface_property sig associatedClock clock
set_interface_property sig associatedReset reset
set_interface_property sig ENABLED true
set_interface_property sig EXPORT_OF ""
set_interface_property sig PORT_NAME_MAP ""
set_interface_property sig SVD_ADDRESS_GROUP ""

add_interface_port sig sig export Input 1

