# TCL File Generated by Component Editor 13.0sp1
# Wed Oct 09 21:00:46 EDT 2019
# DO NOT MODIFY


# 
# avalon_sram "avalon_sram" v1.0
#  2019.10.09.21:00:46
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avalon_sram
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_sram
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_sram
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_sram
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_sram.v VERILOG PATH avalon_sram.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point cpu_sram
# 
add_interface cpu_sram avalon end
set_interface_property cpu_sram addressUnits WORDS
set_interface_property cpu_sram associatedClock clock
set_interface_property cpu_sram associatedReset reset
set_interface_property cpu_sram bitsPerSymbol 8
set_interface_property cpu_sram burstOnBurstBoundariesOnly false
set_interface_property cpu_sram burstcountUnits WORDS
set_interface_property cpu_sram explicitAddressSpan 0
set_interface_property cpu_sram holdTime 0
set_interface_property cpu_sram isMemoryDevice true
set_interface_property cpu_sram linewrapBursts false
set_interface_property cpu_sram maximumPendingReadTransactions 0
set_interface_property cpu_sram readLatency 2
set_interface_property cpu_sram readWaitStates 0
set_interface_property cpu_sram readWaitTime 0
set_interface_property cpu_sram setupTime 0
set_interface_property cpu_sram timingUnits Cycles
set_interface_property cpu_sram writeWaitTime 0
set_interface_property cpu_sram ENABLED true
set_interface_property cpu_sram EXPORT_OF ""
set_interface_property cpu_sram PORT_NAME_MAP ""
set_interface_property cpu_sram SVD_ADDRESS_GROUP ""

add_interface_port cpu_sram address address Input 18
add_interface_port cpu_sram chipselect_n chipselect_n Input 1
add_interface_port cpu_sram read_n read_n Input 1
add_interface_port cpu_sram write_n write_n Input 1
add_interface_port cpu_sram byteenable_n byteenable_n Input 2
add_interface_port cpu_sram writedata writedata Input 16
add_interface_port cpu_sram readdata readdata Output 16
set_interface_assignment cpu_sram embeddedsw.configuration.isFlash 0
set_interface_assignment cpu_sram embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment cpu_sram embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cpu_sram embeddedsw.configuration.isPrintableDevice 0


# 
# connection point sram_ctrl
# 
add_interface sram_ctrl conduit end
set_interface_property sram_ctrl associatedClock clock
set_interface_property sram_ctrl associatedReset reset
set_interface_property sram_ctrl ENABLED true
set_interface_property sram_ctrl EXPORT_OF ""
set_interface_property sram_ctrl PORT_NAME_MAP ""
set_interface_property sram_ctrl SVD_ADDRESS_GROUP ""

add_interface_port sram_ctrl sram_ub_n export Output 1
add_interface_port sram_ctrl sram_lb_n export Output 1
add_interface_port sram_ctrl sram_we_n export Output 1
add_interface_port sram_ctrl sram_oe_n export Output 1
add_interface_port sram_ctrl sram_dq export Bidir 16
add_interface_port sram_ctrl sram_ce_n export Output 1
add_interface_port sram_ctrl sram_addr export Output 18

