# TCL File Generated by Component Editor 13.0sp1
# Sat Oct 05 20:31:18 EDT 2019
# DO NOT MODIFY


# 
# avalon_sdram16 "avalon_sdram16" v1.0
#  2019.10.05.20:31:18
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avalon_sdram16
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_sdram16
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_sdram16
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_sdram16
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_sdram16.v VERILOG PATH ../hw/avalon_sdram16.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point cpu_ctrl
# 
add_interface cpu_ctrl avalon end
set_interface_property cpu_ctrl addressUnits WORDS
set_interface_property cpu_ctrl associatedClock clock
set_interface_property cpu_ctrl associatedReset reset
set_interface_property cpu_ctrl bitsPerSymbol 8
set_interface_property cpu_ctrl burstOnBurstBoundariesOnly false
set_interface_property cpu_ctrl burstcountUnits WORDS
set_interface_property cpu_ctrl explicitAddressSpan 0
set_interface_property cpu_ctrl holdTime 0
set_interface_property cpu_ctrl linewrapBursts false
set_interface_property cpu_ctrl maximumPendingReadTransactions 10
set_interface_property cpu_ctrl readLatency 0
set_interface_property cpu_ctrl readWaitTime 1
set_interface_property cpu_ctrl setupTime 0
set_interface_property cpu_ctrl timingUnits Cycles
set_interface_property cpu_ctrl writeWaitTime 0
set_interface_property cpu_ctrl ENABLED true
set_interface_property cpu_ctrl EXPORT_OF ""
set_interface_property cpu_ctrl PORT_NAME_MAP ""
set_interface_property cpu_ctrl SVD_ADDRESS_GROUP ""

add_interface_port cpu_ctrl chipselect chipselect Input 1
add_interface_port cpu_ctrl address address Input 22
add_interface_port cpu_ctrl byteenable_n byteenable_n Input 2
add_interface_port cpu_ctrl read read Input 1
add_interface_port cpu_ctrl readdata readdata Output 16
add_interface_port cpu_ctrl write write Input 1
add_interface_port cpu_ctrl writedata writedata Input 16
add_interface_port cpu_ctrl waitrequest waitrequest Output 1
add_interface_port cpu_ctrl validdata readdatavalid Output 1
set_interface_assignment cpu_ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment cpu_ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cpu_ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cpu_ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ctrl_sdram
# 
add_interface ctrl_sdram conduit end
set_interface_property ctrl_sdram associatedClock clock
set_interface_property ctrl_sdram associatedReset reset
set_interface_property ctrl_sdram ENABLED true
set_interface_property ctrl_sdram EXPORT_OF ""
set_interface_property ctrl_sdram PORT_NAME_MAP ""
set_interface_property ctrl_sdram SVD_ADDRESS_GROUP ""

add_interface_port ctrl_sdram sdram_addr export Output 12
add_interface_port ctrl_sdram sdram_dq export Bidir 16
add_interface_port ctrl_sdram sdram_ba export Output 2
add_interface_port ctrl_sdram sdram_dqm export Output 2
add_interface_port ctrl_sdram sdram_ras_n export Output 1
add_interface_port ctrl_sdram sdram_cas_n export Output 1
add_interface_port ctrl_sdram sdram_cke export Output 1
add_interface_port ctrl_sdram sdram_we_n export Output 1
add_interface_port ctrl_sdram sdram_cs_n export Output 1

