# TCL File Generated by Component Editor 13.0sp1
# Sat Nov 23 22:22:43 EST 2019
# DO NOT MODIFY


# 
# avalon_audio "avalon_audio" v1.0
#  2019.11.23.22:22:43
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avalon_audio
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_audio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_audio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_audio.v VERILOG PATH ../hw/avalon_audio.v TOP_LEVEL_FILE
add_fileset_file codec_top.v VERILOG PATH ../hw/codec_top.v
add_fileset_file fifo.v VERILOG PATH ../hw/fifo.v
add_fileset_file fifo_ctrl.v VERILOG PATH ../hw/fifo_ctrl.v
add_fileset_file i2c.v VERILOG PATH ../hw/i2c.v
add_fileset_file reg_file.v VERILOG PATH ../hw/reg_file.v
add_fileset_file adc_dac.v VERILOG PATH ../hw/adc_dac.v


# 
# parameters
# 
add_parameter FIFO_SIZE INTEGER 3
set_parameter_property FIFO_SIZE DEFAULT_VALUE 3
set_parameter_property FIFO_SIZE DISPLAY_NAME FIFO_SIZE
set_parameter_property FIFO_SIZE TYPE INTEGER
set_parameter_property FIFO_SIZE UNITS None
set_parameter_property FIFO_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point cpu_ctrl
# 
add_interface cpu_ctrl avalon end
set_interface_property cpu_ctrl addressUnits WORDS
set_interface_property cpu_ctrl associatedClock clock
set_interface_property cpu_ctrl associatedReset reset
set_interface_property cpu_ctrl bitsPerSymbol 8
set_interface_property cpu_ctrl burstOnBurstBoundariesOnly false
set_interface_property cpu_ctrl burstcountUnits WORDS
set_interface_property cpu_ctrl explicitAddressSpan 0
set_interface_property cpu_ctrl holdTime 0
set_interface_property cpu_ctrl linewrapBursts false
set_interface_property cpu_ctrl maximumPendingReadTransactions 0
set_interface_property cpu_ctrl readLatency 0
set_interface_property cpu_ctrl readWaitStates 0
set_interface_property cpu_ctrl readWaitTime 0
set_interface_property cpu_ctrl setupTime 0
set_interface_property cpu_ctrl timingUnits Cycles
set_interface_property cpu_ctrl writeWaitTime 0
set_interface_property cpu_ctrl ENABLED true
set_interface_property cpu_ctrl EXPORT_OF ""
set_interface_property cpu_ctrl PORT_NAME_MAP ""
set_interface_property cpu_ctrl SVD_ADDRESS_GROUP ""

add_interface_port cpu_ctrl audio_chipselect chipselect Input 1
add_interface_port cpu_ctrl audio_write write Input 1
add_interface_port cpu_ctrl audio_read read Input 1
add_interface_port cpu_ctrl audio_writedata writedata Input 32
add_interface_port cpu_ctrl audio_readdata readdata Output 32
add_interface_port cpu_ctrl audio_address address Input 2
set_interface_assignment cpu_ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment cpu_ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cpu_ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cpu_ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ctrl_aud
# 
add_interface ctrl_aud conduit end
set_interface_property ctrl_aud associatedClock clock
set_interface_property ctrl_aud associatedReset reset
set_interface_property ctrl_aud ENABLED true
set_interface_property ctrl_aud EXPORT_OF ""
set_interface_property ctrl_aud PORT_NAME_MAP ""
set_interface_property ctrl_aud SVD_ADDRESS_GROUP ""

add_interface_port ctrl_aud m_clk export Output 1
add_interface_port ctrl_aud b_clk export Output 1
add_interface_port ctrl_aud dac_lr_clk export Output 1
add_interface_port ctrl_aud adc_lr_clk export Output 1
add_interface_port ctrl_aud dacdat export Output 1
add_interface_port ctrl_aud adcdat export Input 1
add_interface_port ctrl_aud i2c_sclk export Output 1
add_interface_port ctrl_aud i2c_sdat export Bidir 1


# 
# connection point ctrl_codec
# 
add_interface ctrl_codec conduit end
set_interface_property ctrl_codec associatedClock clock
set_interface_property ctrl_codec associatedReset reset
set_interface_property ctrl_codec ENABLED true
set_interface_property ctrl_codec EXPORT_OF ""
set_interface_property ctrl_codec PORT_NAME_MAP ""
set_interface_property ctrl_codec SVD_ADDRESS_GROUP ""

add_interface_port ctrl_codec codec_adc_rd export Input 1
add_interface_port ctrl_codec codec_dac_wr export Input 1
add_interface_port ctrl_codec codec_sample_tick export Output 1
add_interface_port ctrl_codec codec_adc_data_out export Output 32
add_interface_port ctrl_codec codec_dac_data_in export Input 32

