# TCL File Generated by Component Editor 13.0sp1
# Sun Oct 27 20:40:18 EDT 2019
# DO NOT MODIFY


# 
# avalon_vga_buffered "avalon_vga_buffered" v1.0
#  2019.10.27.20:40:18
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avalon_vga_buffered
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_vga_buffered
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_vga_buffered
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_vga_buffered
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_vga_buffered.v VERILOG PATH ../hw/avalon_vga_buffered.v TOP_LEVEL_FILE
add_fileset_file fifo.v VERILOG PATH ../hw/fifo.v
add_fileset_file fifo_ctrl.v VERILOG PATH ../hw/fifo_ctrl.v
add_fileset_file palette.v VERILOG PATH ../hw/palette.v
add_fileset_file reg_file.v VERILOG PATH ../hw/reg_file.v
add_fileset_file vga_sync.v VERILOG PATH ../hw/vga_sync.v
add_fileset_file vram_buffered_ctrl.v VERILOG PATH ../hw/vram_buffered_ctrl.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk i_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset i_reset reset Input 1


# 
# connection point ctrl_vga
# 
add_interface ctrl_vga conduit end
set_interface_property ctrl_vga associatedClock clk
set_interface_property ctrl_vga associatedReset reset
set_interface_property ctrl_vga ENABLED true
set_interface_property ctrl_vga EXPORT_OF ""
set_interface_property ctrl_vga PORT_NAME_MAP ""
set_interface_property ctrl_vga SVD_ADDRESS_GROUP ""

add_interface_port ctrl_vga o_vga_hsync export Output 1
add_interface_port ctrl_vga o_vga_vsync export Output 1
add_interface_port ctrl_vga o_vga_rgb export Output 12


# 
# connection point ctrl_sram
# 
add_interface ctrl_sram conduit end
set_interface_property ctrl_sram associatedClock clk
set_interface_property ctrl_sram associatedReset reset
set_interface_property ctrl_sram ENABLED true
set_interface_property ctrl_sram EXPORT_OF ""
set_interface_property ctrl_sram PORT_NAME_MAP ""
set_interface_property ctrl_sram SVD_ADDRESS_GROUP ""

add_interface_port ctrl_sram o_sram_addr export Output 18
add_interface_port ctrl_sram o_sram_ub_n export Output 1
add_interface_port ctrl_sram o_sram_lb_n export Output 1
add_interface_port ctrl_sram o_sram_ce_n export Output 1
add_interface_port ctrl_sram o_sram_oe_n export Output 1
add_interface_port ctrl_sram o_sram_we_n export Output 1
add_interface_port ctrl_sram io_sram_dq export Bidir 16


# 
# connection point cpu_vram
# 
add_interface cpu_vram avalon end
set_interface_property cpu_vram addressUnits WORDS
set_interface_property cpu_vram associatedClock clk
set_interface_property cpu_vram associatedReset reset
set_interface_property cpu_vram bitsPerSymbol 8
set_interface_property cpu_vram burstOnBurstBoundariesOnly false
set_interface_property cpu_vram burstcountUnits WORDS
set_interface_property cpu_vram explicitAddressSpan 0
set_interface_property cpu_vram holdTime 0
set_interface_property cpu_vram linewrapBursts false
set_interface_property cpu_vram maximumPendingReadTransactions 1
set_interface_property cpu_vram readLatency 0
set_interface_property cpu_vram readWaitTime 1
set_interface_property cpu_vram setupTime 0
set_interface_property cpu_vram timingUnits Cycles
set_interface_property cpu_vram writeWaitTime 0
set_interface_property cpu_vram ENABLED true
set_interface_property cpu_vram EXPORT_OF ""
set_interface_property cpu_vram PORT_NAME_MAP ""
set_interface_property cpu_vram SVD_ADDRESS_GROUP ""

add_interface_port cpu_vram o_readdata readdata Output 32
add_interface_port cpu_vram o_readdatavalid readdatavalid Output 1
add_interface_port cpu_vram o_waitrequest waitrequest Output 1
add_interface_port cpu_vram i_address address Input 20
add_interface_port cpu_vram i_chipselect chipselect Input 1
add_interface_port cpu_vram i_read read Input 1
add_interface_port cpu_vram i_write write Input 1
add_interface_port cpu_vram i_writedata writedata Input 32
set_interface_assignment cpu_vram embeddedsw.configuration.isFlash 0
set_interface_assignment cpu_vram embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cpu_vram embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cpu_vram embeddedsw.configuration.isPrintableDevice 0

